#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Oct 19 19:59:50 EDT 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/wayne/xilinx/vivado_install/2025.1/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L axi_uartlite_v2_0_39 -L dist_mem_gen_v8_0_17 -L axi_traffic_gen_v3_0_21 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot themashallah_exdes_tb_behav xil_defaultlib.themashallah_exdes_tb xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L axi_uartlite_v2_0_39 -L dist_mem_gen_v8_0_17 -L axi_traffic_gen_v3_0_21 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot themashallah_exdes_tb_behav xil_defaultlib.themashallah_exdes_tb xil_defaultlib.glbl -log elaborate.log

