# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wayne/FPGA_stuff/FinancialAccleration/TestEnvironments/ip_example_dir/themashallah_ex/themashallah_ex.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xci
# IP: The module: 'axi_traffic_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wayne/FPGA_stuff/FinancialAccleration/TestEnvironments/ip_example_dir/themashallah_ex/themashallah_ex.gen/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wayne/FPGA_stuff/FinancialAccleration/TestEnvironments/ip_example_dir/themashallah_ex/themashallah_ex.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xci
# IP: The module: 'axi_traffic_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wayne/FPGA_stuff/FinancialAccleration/TestEnvironments/ip_example_dir/themashallah_ex/themashallah_ex.gen/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
